version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app    # Mount the app directory for live code updates (2 way relationship)
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"